name: Check Issue Format

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Remind users to use the bug template
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/check_issue.js')
            await script({github, context, core})
